---
title: The Scratch Olympics Weightlifter
hero_image: images/banner.png
description: Make a weightlifter game in Scratch
original_url: https://raspberrypi.org/learning/scratch-olympics-weightlifter
theme: blue
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Progressing through the lift
- title: Animating your weightlifter
- title: Making the lift harder!
- title: Varying the difficulty
- title: "Challenge: Testing the difficulty"
- title: "Challenge: Adding a timer"